select * from employees;

-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
select c.COUNTRY_NAME, r.REGION_NAME
from COUNTRIES c inner join REGIONS r
on c.REGION_ID = r.REGION_ID;

-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select e.FIRST_NAME, j.JOB_TITLE
from JOBS j inner join EMPLOYEES e
on j.JOB_ID = e.JOB_ID;

-- 3. FIND OUT DEPARTMENT_NAME AND CITY
select d.DEPARTMENT_NAME, l.CITY
from DEPARTMENTS d inner join Locations l
on d.LOCATION_ID = l.LOCATION_ID;

-- 4. FIND OUT ALL CITIES AND COUNTRY NAMES
select l.city, c.COUNTRY_NAME
from Locations l inner join Countries c
on l.COUNTRY_ID = c.COUNTRY_ID;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR DEPARTMENT ID 80 OR 40
select e.FIRST_NAME, e.FIRST_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
from EMPLOYEES e inner join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID
where d.DEPARTMENT_ID in (80, 40);

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select l.CITY, c.COUNTRY_NAME, r.REGION_NAME
from LOCATIONS l
         inner join COUNTRIES c
                    on l.COUNTRY_ID = c.COUNTRY_ID
         inner join REGIONS r
                    on r.REGION_ID = c.REGION_ID;

-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select e.FIRST_NAME, j.JOB_TITLE, d.DEPARTMENT_NAME, l.CITY
from EMPLOYEES e
         inner join DEPARTMENTS d
                    on e.DEPARTMENT_ID = d.DEPARTMENT_ID
         inner join JOBS J
                    on e.JOB_ID = J.JOB_ID
         inner join LOCATIONS L
                    on d.LOCATION_ID = L.LOCATION_ID;


-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME
select e.FIRST_NAME, j.JOB_TITLE, d.DEPARTMENT_NAME, l.CITY, c.COUNTRY_NAME, r.REGION_NAME
from EMPLOYEES e
         inner join DEPARTMENTS d
                    on e.DEPARTMENT_ID = d.DEPARTMENT_ID
         inner join JOBS J
                    on e.JOB_ID = J.JOB_ID
         inner join LOCATIONS L
                    on d.LOCATION_ID = L.LOCATION_ID
         inner join COUNTRIES C
                    on c.country_id = L.COUNTRY_ID
         inner join REGIONS R
                    on r.REGION_ID = c.REGION_ID;


--9. FIND OUT EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING WHERE DO NOT HAVE ANY EMPLOYEE.
select e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
from EMPLOYEES e right outer join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID;

--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT
select d.DEPARTMENT_NAME, l.LOCATION_ID, l.COUNTRY_ID
from DEPARTMENTS d right outer join Locations l
                    on l.LOCATION_ID = d.LOCATION_ID
order by 1;


--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
select d.DEPARTMENT_NAME, l.LOCATION_ID, c.COUNTRY_NAME as "Country"
from DEPARTMENTS d
         right outer join Locations l
                    on l.LOCATION_ID = d.LOCATION_ID
         inner join COUNTRIES c
                    on c.COUNTRY_ID = l.COUNTRY_ID
order by 1;

--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS DO NOT HAVE ANY MATCHING EMPLOYEES
select e.FIRST_NAME, d.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES e full outer join DEPARTMENTS d
on e.DEPARTMENT_ID = d.DEPARTMENT_ID;




